# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Rhythm OS BETA
version: "0.1.218-beta"
image: dtconcepts/rhythm-os-addon
slug: rhythm-beta
description: "[BETA] Adaptive lighting that follows the sun"
url: "https://github.com/sticktrk/rhythm-os"
arch:
  - armv7
  - aarch64
  - amd64
init: false
auth_api: true
homeassistant_api: true
map:
  - config:rw
host_network: true
