# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Rhythm Lighting BETA
version: "0.1.192-beta"
image: dtconcepts/rhythm-lighting-addon
slug: rhythm-beta
description: "[BETA] Adaptive lighting that follows the sun"
url: "https://github.com/sticktrk/rhythm-lighting"
arch:
  - armv7
  - aarch64
  - amd64
init: false
auth_api: true
homeassistant_api: true
map:
  - config:rw
ingress: true
ingress_port: 39821
ingress_entry: /
host_network: true
panel_icon: mdi:lightbulb
panel_title: Rhythm Lighting
panel_admin: false
